spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/departmentService
    username: postgres
    password: manager
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084